worker_processes 1;

events {
    worker_connections 1024;
}

http {
    resolver 127.0.0.11 valid=10s ipv6=off;

    server {
        listen 80;
        server_name localhost;

        location /private/ {
            auth_request /authenticate;
            auth_request_set $auth_user $upstream_http_x_auth_user;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_pass http://private-service:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location = /authenticate {
            internal;
            proxy_pass http://auth-service:3001/auth/validate;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header Authorization $http_authorization;
            proxy_set_header X-Auth-Status $upstream_status;
        }

        location / {
            proxy_pass http://private-service:3002;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
